module.exports = {
  preset: "jest-expo",
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@app$": "<rootDir>/src/app",
    "^@app/(.*)$": "<rootDir>/src/app/$1",
    "^@components$": "<rootDir>/src/components",
    "^@components/(.*)$": "<rootDir>/src/components/$1",
    "^@constants$": "<rootDir>/src/constants",
    "^@constants/(.*)$": "<rootDir>/src/constants/$1",
    "^@data$": "<rootDir>/src/data",
    "^@data/(.*)$": "<rootDir>/src/data/$1",
    "^@hooks$": "<rootDir>/src/hooks",
    "^@hooks/(.*)$": "<rootDir>/src/hooks/$1",
    "^@i18n$": "<rootDir>/src/i18n",
    "^@i18n/(.*)$": "<rootDir>/src/i18n/$1",
    "^@lib$": "<rootDir>/src/lib",
    "^@lib/(.*)$": "<rootDir>/src/lib/$1",
    "^@store$": "<rootDir>/src/store",
    "^@store/(.*)$": "<rootDir>/src/store/$1",
    "^@types$": "<rootDir>/src/types",
    "^@types/(.*)$": "<rootDir>/src/types/$1",
    "^@utils$": "<rootDir>/src/utils",
    "^@utils/(.*)$": "<rootDir>/src/utils/$1",
    "^@context/(.*)$": "<rootDir>/src/context/$1",
  },
  testPathIgnorePatterns: ["/node_modules/", "/android/", "/ios/"],
};
